import type { BoardFigure, HqModule, ModelProfile, PermissionRule } from "./types";

export const hqModules: HqModule[] = [
  {
    id: "workspace-modes",
    title: "Workspace & Modes",
    subtitle: "Sépare les contextes par mode configuré du workspace actif.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "command-center",
    title: "Command Center",
    subtitle: "Une entrée rapide pour parler, booker, noter, analyser et créer.",
    status: "foundation",
    autonomyLevel: 2,
  },
  {
    id: "joris-brain",
    title: "Joris Brain",
    subtitle: "Cerveau serveur, mémoire, modèles IA, Board et outils.",
    status: "foundation",
    autonomyLevel: 2,
  },
  {
    id: "permission-center",
    title: "Permission Center",
    subtitle: "Ce que Joris peut faire seul, demander ou ne jamais faire.",
    status: "foundation",
    autonomyLevel: 5,
  },
  {
    id: "ceo-brief",
    title: "CEO Brief",
    subtitle: "Brief matin/soir avec cash, agenda, risques et action numéro 1.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "joris-book",
    title: "Joris Book",
    subtitle: "Rendez-vous et rappels en langage naturel, FR-CA par défaut.",
    status: "foundation",
    autonomyLevel: 3,
  },
  {
    id: "voice",
    title: "Voix FR-CA",
    subtitle: "Micro mobile, transcription fr-CA, ElevenLabs, puis Twilio.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "knowledge-vault",
    title: "Knowledge Vault",
    subtitle: "Documents, décisions, SOPs, notes et recherche interne par workspace.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "financial-advisor-mode",
    title: "Mode conseiller financier",
    subtitle: "Préparation, suivis, contenu éducatif et garde-fous stricts pour Eric et futurs clients.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "real-estate-mode",
    title: "Mode immobilier",
    subtitle: "Listings, suivis, rendez-vous, contenu local et workflow courtier sans contaminer le core.",
    status: "planned",
    autonomyLevel: 2,
  },
  {
    id: "money-cockpit",
    title: "Runway & Money",
    subtitle: "Cash, runway, coûts IA, paliers et objectifs millionnaires.",
    status: "planned",
    autonomyLevel: 2,
  },
];

export const modelProfiles: ModelProfile[] = [
  {
    id: "claude-sonnet-4-6",
    label: "Claude Sonnet 4.6",
    provider: "anthropic",
    defaultUse: "Décisions entrepreneuriales, Board, ton FR-CA, réponses vocales importantes.",
    costTier: "medium",
    strengths: ["jugement", "stratégie", "écriture", "raisonnement long"],
  },
  {
    id: "gpt-4o-mini",
    label: "ChatGPT économique",
    provider: "openai",
    defaultUse: "Tâches rapides, reformulation, brouillons simples, fallback.",
    costTier: "low",
    strengths: ["vitesse", "coût", "formats structurés"],
  },
  {
    id: "gpt-4o",
    label: "ChatGPT premium",
    provider: "openai",
    defaultUse: "Créativité, génération structurée, compatibilité écosystème.",
    costTier: "medium",
    strengths: ["créativité", "outillage", "multimodalité"],
  },
  {
    id: "gemini-flash",
    label: "Gemini économique",
    provider: "google",
    defaultUse: "Contexte long, synthèse documentaire et fallback faible coût.",
    costTier: "low",
    strengths: ["contexte long", "coût", "résumé"],
  },
  {
    // Access via OpenRouter gateway — useful as unified fallback when direct provider keys are missing.
    // Requires OPENROUTER_API_KEY. HTTP client: baseURL https://openrouter.ai/api/v1 (OpenAI-compatible).
    id: "openrouter/anthropic/claude-sonnet-4-6",
    label: "Claude Sonnet (via OpenRouter)",
    provider: "openrouter",
    defaultUse: "Fallback premium via OpenRouter quand la clé Anthropic directe est absente.",
    costTier: "medium",
    strengths: ["jugement", "stratégie", "écriture", "fallback unifié"],
  },
  {
    id: "openrouter/mistralai/mistral-small-3.2-24b",
    label: "Mistral Small (via OpenRouter)",
    provider: "openrouter",
    defaultUse: "Fallback économique européen via OpenRouter — RGPD-friendly, rapide, faible coût.",
    costTier: "low",
    strengths: ["vitesse", "coût", "multilingual", "RGPD"],
  },
];

export const permissionRules: PermissionRule[] = [
  {
    id: "internal-draft",
    action: "Préparer un brouillon, une tâche ou une SOP interne",
    level: 2,
    requiresConfirmation: false,
    reason: "Action interne réversible.",
  },
  {
    id: "calendar-simple",
    action: "Créer un rendez-vous personnel simple sans invitation externe",
    level: 3,
    requiresConfirmation: false,
    reason: "Faible risque, réversible, utile au quotidien.",
  },
  {
    id: "calendar-external",
    action: "Envoyer une invitation externe, déplacer ou annuler un événement partagé",
    level: 4,
    requiresConfirmation: true,
    reason: "Impact sur d'autres personnes.",
  },
  {
    id: "external-send",
    action: "Envoyer un message, publier, appeler ou dépenser",
    level: 5,
    requiresConfirmation: true,
    reason: "Action externe ou financière.",
  },
];

export const billionaireBoard: BoardFigure[] = [
  {
    id: "hormozi",
    name: "Alex Hormozi",
    domain: "Offre, pricing, acquisition et unit economics.",
    frameworks: ["Value Equation", "Grand Slam Offer", "Core Four", "Niche Slap"],
    lexicon: ["dream outcome", "make them feel stupid saying no", "volume negates luck"],
    bias: "Peut sur-optimiser l'offre au détriment de la marque et du contexte local.",
    bestFor: "Pricing, offre, packaging, acquisition, décision go/no-go.",
  },
  {
    id: "brunson",
    name: "Russell Brunson",
    domain: "Funnels, storytelling et conversion.",
    frameworks: ["Hook Story Offer", "Value Ladder", "Perfect Webinar", "Dream 100"],
    lexicon: ["big domino", "false beliefs", "value ladder"],
    bias: "Peut pousser vers des funnels trop lourds pour une étape bootstrap.",
    bestFor: "Messages, landing pages, offres séquencées, webinars.",
  },
  {
    id: "kennedy",
    name: "Dan Kennedy",
    domain: "Positionnement premium et marketing direct.",
    frameworks: ["Market Message Media Math", "No B.S.", "Marketing to the Affluent"],
    lexicon: ["No B.S.", "riches in niches", "price elasticity is psychological"],
    bias: "Très direct-response, parfois trop agressif pour certains marchés.",
    bestFor: "Pricing, copy, discipline commerciale, offre premium.",
  },
  {
    id: "cardone",
    name: "Grant Cardone",
    domain: "Volume de vente, omniprésence et action massive.",
    frameworks: ["10X Rule", "4 Degrees of Action", "Obscurity is the problem"],
    lexicon: ["10X", "massive action", "dominate don't compete"],
    bias: "Risque de burnout et de volume sans finesse.",
    bestFor: "Sortir de l'inertie, outbound, gestion du rejet.",
    disclosure: "Mentionner Pino v. Cardone Capital si conseil immobilier passif.",
  },
  {
    id: "belfort",
    name: "Jordan Belfort",
    domain: "Persuasion, tonality et closing.",
    frameworks: ["Straight Line", "Three Tens", "Looping", "First 4 Seconds"],
    lexicon: ["straight line", "three tens", "tonality"],
    bias: "Origines criminelles et risque de manipulation si mal utilisé.",
    bestFor: "Scripts d'appel, objections, ton, closing court terme.",
    disclosure: "Rappeler Stratton Oakmont et restitution non soldée en contexte vente.",
  },
  {
    id: "godin",
    name: "Seth Godin",
    domain: "Marque, permission et différenciation.",
    frameworks: ["Purple Cow", "Smallest Viable Market", "Permission Marketing", "The Dip"],
    lexicon: ["remarkable", "people like us do things like this", "smallest viable market"],
    bias: "Moins tactique sur la vente directe immédiate.",
    bestFor: "Positionnement, marque, permission, marché minimal viable.",
  },
  {
    id: "garyvee",
    name: "Gary Vaynerchuk",
    domain: "Attention, contenu organique et distribution.",
    frameworks: ["Day Trading Attention", "Document Don't Create", "Jab Jab Jab Right Hook"],
    lexicon: ["underpriced attention", "cloud and dirt", "document don't create"],
    bias: "Peut pousser trop de volume de contenu pour un fondateur solo.",
    bestFor: "Distribution, contenu, personal brand, attention émergente.",
  },
  {
    id: "robbins",
    name: "Tony Robbins",
    domain: "Énergie, état mental et performance.",
    frameworks: ["State Story Strategy", "RPM", "Six Human Needs"],
    lexicon: ["where focus goes energy flows", "massive action", "CANI"],
    bias: "Peut psychologiser ce qui est parfois un problème structurel.",
    bestFor: "Mindset, énergie, blocage, discipline durable.",
  },
];
