import type { SkillProfile } from "./types";

export const skillsCatalog: SkillProfile[] = [
  // ── Money ────────────────────────────────────────────────────────────────
  {
    id: "cash.snapshot",
    label: "Cash Snapshot",
    category: "money",
    description: "Produit un résumé du cash disponible, du runway estimé et des coûts IA du mois.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["money"],
    inputs: [{ name: "period", type: "string", required: false, note: "ex. '2026-05'" }],
    outputs: [{ name: "snapshot", type: "CashSnapshot", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Retourne cash/runway/coûts sans aucune transaction"],
    outputConstraint: "Lecture seule — aucune transaction ni virement",
  },
  {
    id: "runway.calc",
    label: "Runway Calculator",
    category: "money",
    description: "Calcule le runway en semaines selon les dépenses actuelles et les réserves.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["money"],
    inputs: [
      { name: "burnCents", type: "number", required: true },
      { name: "reserveCents", type: "number", required: true },
    ],
    outputs: [{ name: "weeks", type: "number", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Calcule le runway en semaines, lecture seule"],
    outputConstraint: "Lecture seule — aucune transaction ni virement",
  },

  // ── Sales / CRM ──────────────────────────────────────────────────────────
  {
    id: "lead.triage",
    label: "Lead Triage",
    category: "sales",
    description: "Évalue et classe les leads entrants par priorité selon les critères ICP définis.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["scout"],
    inputs: [{ name: "leads", type: "Lead[]", required: true }],
    outputs: [{ name: "ranked", type: "RankedLead[]", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Classe les leads par priorité sans contact externe"],
    outputConstraint: "Analyse seulement — aucun contact externe",
  },
  {
    id: "script.call",
    label: "Call Script",
    category: "sales",
    description: "Génère un script d'appel structuré (Straight Line) adapté au profil du lead.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["closer"],
    inputs: [{ name: "leadProfile", type: "LeadProfile", required: true }],
    outputs: [{ name: "script", type: "string", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Produit un brouillon de script — aucun envoi"],
    outputConstraint: "Brouillon interne — aucun envoi sans confirmation CEO niveau 5",
  },
  {
    id: "followup.sequence",
    label: "Follow-up Sequence",
    category: "sales",
    description: "Crée une séquence de 3 à 5 messages de suivi pour un lead ou un pipeline.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["closer"],
    inputs: [{ name: "pipeline", type: "PipelineContext", required: true }],
    outputs: [{ name: "sequence", type: "Message[]", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Produit une séquence brouillon — aucun envoi"],
    outputConstraint: "Brouillon interne — aucun envoi sans confirmation CEO niveau 5",
  },

  // ── Marketing ────────────────────────────────────────────────────────────
  {
    id: "opportunity.scan",
    label: "Opportunity Scan",
    category: "marketing",
    description: "Scanne les signaux de marché et identifie les opportunités selon le contexte actif.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["scout"],
    inputs: [{ name: "context", type: "WorkspaceContext", required: true }],
    outputs: [{ name: "opportunities", type: "Opportunity[]", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Produit un rapport interne — aucune publication"],
    outputConstraint: "Rapport interne — aucune publication",
  },

  // ── Briefings ────────────────────────────────────────────────────────────
  {
    id: "brief.generate",
    label: "CEO Brief",
    category: "briefings",
    description: "Génère le brief matin ou soir : agenda, leads, cash, risques et action numéro 1.",
    status: "partial",
    autonomyLevel: 2,
    assignedRoles: ["orchestrator"],
    inputs: [
      { name: "date", type: "string", required: true },
      { name: "sources", type: "string[]", required: true },
    ],
    outputs: [{ name: "brief", type: "CeoBriefSnapshot", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Affichage interne — aucun envoi externe automatique"],
    outputConstraint: "Affichage interne — aucun envoi externe automatique",
  },
  {
    id: "mission.plan",
    label: "Mission Dry-Run Plan",
    category: "briefings",
    description:
      "Produit un plan d'exécution dry-run pour une mission. approvalConfirmed toujours false. requiresConfirmation toujours true.",
    status: "active",
    autonomyLevel: 2,
    assignedRoles: ["orchestrator"],
    inputs: [{ name: "mission", type: "Mission", required: true }],
    outputs: [{ name: "plan", type: "MissionExecutorPlan", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Dry-run uniquement — approvalConfirmed=false, aucune exécution"],
    outputConstraint: "Dry-run uniquement — live executor verrouillé jusqu'au Red Team pass",
  },
  {
    id: "board.consult",
    label: "Board Consult",
    category: "briefings",
    description:
      "Consulte le Billionaire Board pour un angle stratégique sur une décision ou une offre.",
    status: "partial",
    autonomyLevel: 1,
    assignedRoles: ["orchestrator"],
    inputs: [{ name: "question", type: "string", required: true }],
    outputs: [{ name: "angle", type: "string", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Lecture/analyse seule — aucune écriture"],
  },

  // ── Customer Ops ─────────────────────────────────────────────────────────
  {
    id: "calendar.book",
    label: "Calendar Book",
    category: "customer-ops",
    description: "Crée un rendez-vous ou un rappel en langage naturel, FR-CA par défaut.",
    status: "active",
    autonomyLevel: 3,
    assignedRoles: ["orchestrator"],
    inputs: [{ name: "intent", type: "CalendarIntent", required: true }],
    outputs: [{ name: "event", type: "CalendarEvent", required: true }],
    sideEffects: "reversible-write",
    canWriteDB: true,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: ["action"],
    testsRequired: [
      "Crée un événement interne réversible et journalise une action",
      "Invitation externe → escalade au niveau 4 (approbation)",
    ],
    outputConstraint: "Invitation externe nécessite confirmation niveau 4",
  },

  // ── Legal / Admin ────────────────────────────────────────────────────────
  {
    id: "sop.draft",
    label: "SOP Draft",
    category: "legal-admin",
    description: "Rédige une procédure opérationnelle standard (SOP) pour un processus interne.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["operator"],
    inputs: [{ name: "process", type: "string", required: true }],
    outputs: [{ name: "sop", type: "string", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Brouillon interne — aucune publication ni envoi"],
    outputConstraint: "Brouillon interne — aucune publication ni envoi",
  },

  // ── Dev / Code ───────────────────────────────────────────────────────────
  {
    id: "spec.draft",
    label: "Spec Draft",
    category: "dev-code",
    description: "Produit une spécification technique structurée pour un MVP ou une fonctionnalité.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["builder"],
    inputs: [{ name: "feature", type: "string", required: true }],
    outputs: [{ name: "spec", type: "string", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Document interne — aucun déploiement"],
    outputConstraint: "Document interne — aucun déploiement sans approbation CEO",
  },
  {
    id: "mvp.plan",
    label: "MVP Plan",
    category: "dev-code",
    description: "Structure un plan MVP : objectif, scope minimal, étapes et critères de succès.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["builder"],
    inputs: [{ name: "idea", type: "string", required: true }],
    outputs: [{ name: "plan", type: "MvpPlan", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Plan interne — aucune exécution"],
    outputConstraint: "Plan interne — aucune exécution sans validation CEO",
  },

  // ── Automation ───────────────────────────────────────────────────────────
  {
    id: "workflow.map",
    label: "Workflow Map",
    category: "automation",
    description: "Cartographie un workflow métier répétable et identifie les points d'automatisation.",
    status: "planned",
    autonomyLevel: 2,
    assignedRoles: ["operator"],
    inputs: [{ name: "process", type: "string", required: true }],
    outputs: [{ name: "map", type: "WorkflowMap", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Analyse interne — aucune modification de systèmes"],
    outputConstraint: "Analyse interne — aucune modification de systèmes sans approbation CEO",
  },
  {
    id: "risk.review",
    label: "Risk Review",
    category: "automation",
    description:
      "Évalue les risques d'une mission ou d'un plan. Sign-off requis avant live executor unlock.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["auditor"],
    inputs: [{ name: "missionOrPlan", type: "Mission | MissionExecutorPlan", required: true }],
    outputs: [{ name: "riskReport", type: "RiskReport", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Évaluation seule — rôle bloquant, aucune exécution propre"],
    outputConstraint: "Évaluation uniquement — rôle bloquant, pas d'exécution propre",
  },
  {
    id: "redteam.pass",
    label: "Red Team Pass",
    category: "automation",
    description:
      "Conduit la red team review complète des guardrails Mission Control avant toute activation live.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["auditor"],
    inputs: [{ name: "guardrails", type: "GuardrailSet", required: true }],
    outputs: [{ name: "signoff", type: "RedTeamSignoff", required: true }],
    sideEffects: "none",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Sign-off requis — ne peut pas s'auto-valider"],
    outputConstraint: "Sign-off requis — ne peut pas s'auto-valider",
  },

  // ── Memory (Scribe) ────────────────────────────────────────────────────────
  {
    id: "memory.save",
    label: "Memory Save",
    category: "memory",
    description: "Sauvegarde une décision ou un fait important dans la mémoire du workspace.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["memory"],
    inputs: [{ name: "entry", type: "MemoryEntry", required: true }],
    outputs: [{ name: "savedId", type: "string", required: true }],
    sideEffects: "reversible-write",
    canWriteDB: true,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: ["action"],
    testsRequired: [
      "Écrit en mémoire du workspace et journalise une action",
      "Aucune fuite cross-workspace",
    ],
    outputConstraint: "Mémoire interne du workspace — aucune fuite cross-workspace",
  },
  {
    id: "daily.log",
    label: "Daily Log",
    category: "memory",
    description: "Compile le journal quotidien des décisions, actions et apprentissages.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["memory"],
    inputs: [
      { name: "date", type: "string", required: true },
      { name: "events", type: "LedgerEvent[]", required: true },
    ],
    outputs: [{ name: "logId", type: "string", required: true }],
    sideEffects: "reversible-write",
    canWriteDB: true,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: ["action"],
    testsRequired: ["Compile et écrit le journal du jour + journalise une action"],
    outputConstraint: "Journal interne — aucune publication externe",
  },
  {
    id: "summary.generate",
    label: "Summary Generate",
    category: "memory",
    description: "Résume une mission ou une conversation en points actionnables.",
    status: "planned",
    autonomyLevel: 1,
    assignedRoles: ["memory"],
    inputs: [{ name: "source", type: "string", required: true }],
    outputs: [{ name: "summary", type: "string", required: true }],
    sideEffects: "internal-draft",
    canWriteDB: false,
    canTriggerExternal: false,
    requiresHumanApproval: false,
    logsRequired: [],
    testsRequired: ["Résumé interne — ne ré-écrit jamais le ledger"],
    outputConstraint: "Résumé interne — ne ré-écrit jamais le ledger",
  },
];

export const CATEGORY_LABELS: Record<SkillProfile["category"], string> = {
  money: "Money",
  sales: "Sales / CRM",
  marketing: "Marketing",
  briefings: "Briefings",
  "customer-ops": "Customer Ops",
  "legal-admin": "Legal / Admin",
  "dev-code": "Dev / Code",
  automation: "Automation",
  memory: "Memory",
};
