import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {createJiti} from 'jiti';import {createClient} from '@supabase/supabase-js';
import {createHash} from 'node:crypto';
const jiti=createJiti(import.meta.url,{alias:{'@':path.join(process.cwd(),'src'),'server-only':path.join(process.cwd(),'src/scripts/smoke/server-only-stub.mjs')}});
const {createDevelopmentService}=await jiti.import('./development-mission.ts');const {buildOpenHandsSubmission}=await jiti.import('./openhands-submission.ts');
const {createOpenHandsConfirmationService}=await jiti.import('./openhands-confirmation.ts');const {createOpenHandsAuthorityStore,openHandsAuthorizationId}=await jiti.import('./openhands-authority-store.ts');
const {OPENHANDS_RESERVATION_KEY}=await jiti.import('./openhands-reservation.ts');
let original;await createDevelopmentService({enabled:()=>true,store:()=>({save:async(m)=>{original=m;return m;},load:async()=>original})}).create({requestId:'714ac9b7-6bce-4eb4-b3bd-08d3df8ad46e',title:'Synthetic',objective:'Confirmation',scope:'One file',acceptanceCriteria:'Tests pass'},{workspaceId:'test-w',modeId:'hq',actorId:'owner'});
const req={missionId:original.id,expectedUpdatedAt:original.updatedAt,commitSha:'a'.repeat(40),executorVersion:'1.2.3',budget:{maxCostCents:10,maxTokens:100,maxIterations:1,timeoutSeconds:60}};
const ctx={workspaceId:'test-w',actorId:'owner'},now=Date.parse('2026-09-30T12:00:00Z');const d=buildOpenHandsSubmission(original,ctx.workspaceId,req).dossier;const confirm={confirm:true,expectedPayloadHash:d.payloadHash};
function authorityDb(){const rows=new Map();let writes=0;let failRead=false;const client=createClient('https://synthetic.invalid','test-key',{auth:{persistSession:false},global:{fetch:async(url,init)=>{const u=new URL(url);if(init.method==='POST'){writes++;const row=JSON.parse(init.body);assert.ok(new Headers(init.headers).get('prefer').includes('resolution=ignore-duplicates'));if(!rows.has(row.id))rows.set(row.id,{...row,created_at:new Date(now).toISOString()});return new Response(null,{status:201});}if(failRead){failRead=false;return new Response(JSON.stringify({message:'synthetic read unavailable'}),{status:400});}return new Response(JSON.stringify(rows.get(u.searchParams.get('id').slice(3))??null),{status:200,headers:{'content-type':'application/json'}});}}});return {store:createOpenHandsAuthorityStore(client),rows,failNextRead:()=>{failRead=true;},writes:()=>writes};}
function fixture(fail=false){let row=structuredClone(original);let writes=0,audits=0;const db=authorityDb();const store={load:async()=>structuredClone(row),compareAndSwap:async(m,r)=>{if(row.updatedAt!==m.updatedAt||JSON.stringify(row.input)!==JSON.stringify(m.input))return null;row={...row,input:{...row.input,[OPENHANDS_RESERVATION_KEY]:r},updatedAt:new Date(now+(++writes)).toISOString()};return structuredClone(row);},audit:async()=>{audits++;return 'audit-id';}};return {db,mutate:(patch)=>{row={...row,...patch};},stats:()=>({writes,audits}),service:createOpenHandsConfirmationService({store:()=>store,authority:()=>fail?{persist:async()=>{throw Error('unknown persistence');}}:db.store,now:()=>now})};}
test('canonical ledger approval insert-ignore concurrent identity; replay retains original expiry and binds actual actor/full dossier',async()=>{const db=authorityDb();const [a,b]=await Promise.all([db.store.persist(d,'owner',now),db.store.persist(d,'owner',now+1)]);assert.deepEqual(a,b);assert.equal(db.rows.size,1);assert.equal(a.id,openHandsAuthorizationId(d,'owner'));assert.notEqual(a.id,openHandsAuthorizationId(d,'another'));assert.equal(a.expiresAt,new Date(now+600000).toISOString());const row=db.rows.get(a.id);assert.deepEqual(row.payload,JSON.parse(JSON.stringify(d)));row.user_id='foreign';await assert.rejects(db.store.persist(d,'owner',now));});
test('prepare and wrong expected hash never persist authority or reserve',async()=>{const f=fixture();assert.equal((await f.service(ctx,req)).status,'prepared');assert.equal((await f.service(ctx,req,{...confirm,expectedPayloadHash:'f'.repeat(64)})).status,'dossier_changed');assert.equal(f.db.writes(),0);assert.equal(f.stats().writes,0);});
test('concurrent confirmations share one durable approval; replay avoids new approval/audit writes',async()=>{const f=fixture();const results=await Promise.all([f.service(ctx,req,confirm),f.service(ctx,req,confirm)]);assert.equal(results.filter(r=>r.status==='reserved').length,1);assert.equal(f.db.rows.size,1);assert.equal(f.stats().audits,1);const writes=f.db.writes();assert.equal((await f.service(ctx,req,confirm)).status,'already_reserved');assert.equal(f.db.writes(),writes);assert.equal(f.stats().audits,1);assert.equal((await f.service(ctx,req)).status,'already_reserved');assert.equal(f.db.writes(),writes);});
test('failed authority persistence blocks reservation and reports unknown; foreign workspace blocked',async()=>{const f=fixture(true);assert.equal((await f.service(ctx,req,confirm)).status,'authorization_outcome_unknown');assert.deepEqual(f.stats(),{writes:0,audits:0});assert.equal((await f.service({...ctx,workspaceId:'foreign'},req,confirm)).status,'not_found');});
test('expired canonical authorization is not silently replaced or extended',async()=>{const db=authorityDb();const a=await db.store.persist(d,'owner',now);await assert.rejects(db.store.persist(d,'owner',now+600000));assert.equal(db.rows.size,1);assert.equal(db.rows.get(a.id).metadata.authorization.expiresAt,a.expiresAt);});

test('racing mission change after approval persistence loses CAS and never writes reservation audit',async()=>{const f=fixture();const persist=f.db.store.persist;f.db.store.persist=async(...args)=>{const a=await persist(...args);f.mutate({updatedAt:'2026-10-01T00:00:00Z',title:'changed concurrently'});return a;};const result=await f.service(ctx,req,confirm);assert.equal(result.status,'conflict');assert.deepEqual(f.stats(),{writes:0,audits:0});assert.equal(f.db.rows.size,1);});

test('lost canonical read after committed approval recovers same record on explicit retry',async()=>{const f=fixture();f.db.failNextRead();assert.equal((await f.service(ctx,req,confirm)).status,'authorization_outcome_unknown');assert.equal(f.db.rows.size,1);assert.deepEqual(f.stats(),{writes:0,audits:0});const first=[...f.db.rows.values()][0].metadata.authorization;assert.equal((await f.service(ctx,req,confirm)).status,'reserved');assert.equal(f.db.rows.size,1);assert.deepEqual([...f.db.rows.values()][0].metadata.authorization,first);assert.equal(f.stats().audits,1);});

test('confirmation persists exact memory dossier and refuses an older preview after memory attachment',async()=>{
 const entity={id:'anchor',namespace:'org:project-a',type:'Project',source:'reviewed',properties:{status:'verified'}};
 const content=JSON.stringify({centerEntity:entity,entities:[entity],relations:[],provenance:[{id:'anchor',source:'reviewed',originId:null,confidence:null}]});
 const hashInput={contractVersion:1,sourceTool:'agentmemory_context_pack',workspaceId:ctx.workspaceId,projectId:'project-a',namespace:'org:project-a',centerEntityId:'anchor',retrievedAtIso:new Date(now).toISOString(),content,redactionsApplied:0};
 const memory={...hashInput,contentChars:content.length,snapshotHash:createHash('sha256').update(JSON.stringify(hashInput)).digest('hex')};
 const f=fixture();f.mutate({input:{...original.input,_openhandsMemory:memory}});
 assert.equal((await f.service(ctx,req,confirm)).status,'dossier_changed');assert.equal(f.db.writes(),0);
 const preview=await f.service(ctx,req);assert.equal(preview.status,'prepared');assert.equal(preview.dossier.contractVersion,2);
 const confirmation={confirm:true,expectedPayloadHash:preview.dossier.payloadHash};
 assert.equal((await f.service(ctx,req,confirmation)).status,'reserved');
 assert.deepEqual([...f.db.rows.values()][0].payload.memory,preview.dossier.memory);
 assert.equal((await f.service(ctx,req,confirmation)).status,'already_reserved');
});
