"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import type {DevelopmentInput,DevelopmentReceipt} from "@/server/missions/development-mission";
const fields=[{key:"title",label:"Titre",max:200},{key:"objective",label:"Objectif",max:4000},{key:"scope",label:"Périmètre autorisé (fichiers, changements et exclusions)",max:1000},{key:"acceptanceCriteria",label:"Critères d’acceptation et validations attendues",max:2000}] as const;
export function DevelopmentMissionForm({workspaceId}:{workspaceId:string}){
 const [values,setValues]=useState({title:"",objective:"",scope:"",acceptanceCriteria:""});const [requestId,setRequestId]=useState<string|null>(null);const [result,setResult]=useState<DevelopmentReceipt|{status:"request_denied"|"invalid_request"}|null>(null);const [busy,setBusy]=useState(false);const [frozen,setFrozen]=useState(false);const [storageError,setStorageError]=useState(false);const lock=useRef(false);const payload=useRef<DevelopmentInput|null>(null);const router=useRouter();const key=`hq:development-mission:${workspaceId}`;
 async function run(readOnly:boolean,retry=false){
  if(lock.current||(!readOnly&&requestId&&!retry))return;lock.current=true;setBusy(true);
  let id:string;
  try{const previous=sessionStorage.getItem(key);if(previous&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(previous))throw Error();if(readOnly&&!requestId&&!previous){setResult({status:"not_found"});lock.current=false;setBusy(false);return;}id=requestId??previous??crypto.randomUUID();if(previous&&!requestId)readOnly=true;sessionStorage.setItem(key,id);setRequestId(id);setStorageError(false);}catch{setStorageError(true);lock.current=false;setBusy(false);return;}
  if(!readOnly&&!payload.current){payload.current={requestId:id,...values};setFrozen(true);}
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
  try{const response=await fetch(readOnly?`/api/missions/development?requestId=${encodeURIComponent(id)}`:"/api/missions/development",{method:readOnly?"GET":"POST",cache:"no-store",signal:controller.signal,...(!readOnly?{headers:{"Content-Type":"application/json"},body:JSON.stringify(payload.current)}:{})});const body=await response.json();
   if((response.status===403&&body.status==="request_denied")||(response.status===400&&body.status==="invalid_request")){setResult(body);return;}
   if(!response.ok||!["saved","disabled","unavailable","outcome_unknown","not_found","conflict"].includes(body.status))throw Error();
   if(body.status==="saved"&&(typeof body.missionId!=="string"||typeof body.title!=="string"||body.executionRequested!==false))throw Error();setResult(body);if(body.status==="saved")router.refresh();
  }catch{setResult({status:readOnly?"unavailable":"outcome_unknown"});}finally{clearTimeout(timer);controller.abort();lock.current=false;setBusy(false);}
 }
 const messages:Record<string,string>={disabled:"Création durable désactivée sur cette instance.",unavailable:"Stockage durable indisponible. Vérifie le reçu avant toute reprise.",outcome_unknown:"Résultat incertain. Aucun nouvel identifiant ni renvoi automatique : vérifie le reçu.",not_found:"Aucune mission retrouvée avec cet identifiant. Tu peux réessayer le même contenu explicitement.",conflict:"Cet identifiant correspond à une autre intention. Aucun écrasement effectué.",request_denied:"Origine refusée avant écriture. Corrige la connexion puis réessaie avec le même identifiant.",invalid_request:"Requête invalide, aucune écriture demandée."};
 return <section id="development-mission" className="rounded-2xl border border-amber-500/20 bg-neutral-950/50 p-5" aria-labelledby="development-title"><h2 id="development-title" className="text-lg font-semibold text-white">Créer une mission de développement</h2><p className="mt-2 text-sm text-neutral-400">Enregistre un brouillon durable, sans lancer d’agent. Le périmètre et les critères accompagneront son transfert explicite vers Paperclip.</p>
 <form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void run(false);}}>{fields.map(field=><label key={field.key} className="block text-sm text-neutral-300">{field.label}<textarea required maxLength={field.max} rows={field.key==="title"?1:3} disabled={busy||frozen} value={values[field.key]} onChange={e=>setValues({...values,[field.key]:e.target.value})} className="mt-2 block w-full rounded-lg border border-neutral-700 bg-neutral-900 p-3 disabled:opacity-60" /></label>)}{!requestId&&<button disabled={busy||fields.some(field=>!values[field.key].trim())} className="min-h-11 rounded-lg bg-amber-400 px-4 font-semibold text-neutral-950 disabled:opacity-50">Enregistrer le brouillon</button>}</form>
 <p role="status" className="mt-3 text-sm text-neutral-300">{busy?"Vérification…":result?.status==="saved"?`Mission enregistrée : ${result.title}. Aucun agent lancé.`:result?messages[result.status]:""}</p>{storageError&&<p role="alert" className="text-sm text-amber-200">Suivi de session indisponible ou corrompu : aucun nouvel envoi.</p>}
 <button disabled={busy} onClick={()=>void run(true)} className="mt-3 min-h-11 rounded-lg border border-neutral-700 px-4 text-sm text-amber-200">Vérifier le dernier reçu</button>{requestId&&<p className="mt-2 break-all text-xs text-neutral-500">Identifiant de demande : {requestId}</p>}
 {requestId&&["not_found","request_denied","invalid_request","disabled"].includes(result?.status??"")&&<button disabled={busy||fields.some(field=>!values[field.key].trim())||storageError} onClick={()=>void run(false,true)} className="mt-3 min-h-11 rounded-lg border border-neutral-700 px-4 text-sm text-amber-200">Réessayer avec le même identifiant</button>}
 {result?.status==="saved"&&<div className="mt-3"><p className="break-all text-xs text-neutral-500">Mission : {result.missionId}</p><button disabled={busy} onClick={()=>{try{sessionStorage.removeItem(key);}catch{setStorageError(true);return;}setRequestId(null);setResult(null);setValues({title:"",objective:"",scope:"",acceptanceCriteria:""});payload.current=null;setFrozen(false);}} className="mt-3 min-h-11 text-amber-200">Préparer une autre mission</button></div>}
 <p className="mt-3 text-xs text-neutral-500">Seul l’identifiant est conservé pour cette session et ce projet. Après actualisation, ressaisis le contenu original si une reprise est nécessaire.</p></section>;
}
